name:                graphics-primitives-opengl
version:             0.1.0.0
github:              "CLowcay/haskell-native-gui"
license:             BSD3
author:              "Callum Lowcay"
maintainer:          "cwslowcay@gmail.com"
copyright:           "2019 Callum Lowcay"

description:         Please see the README on GitHub at <https://github.com/CLowcay/haskell-native-gui#readme>

dependencies:
- OpenGL >= 3.0 && < 3.1
- StateVar >= 1.1 && < 1.2
- base >= 4.7 && < 5
- bytestring >= 0.10 && < 0.11
- mtl >= 2.2.2 && < 2.3
- sdl2 >= 2.4 && < 2.5

library:
  source-dirs: src
  ghc-options: -Wall

executables:
  example:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graphics-primitives-opengl

tests:
  graphics-primitives-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graphics-primitives-opengl
