name:                graphics-primitives
version:             0.1.0.0
github:              "CLowcay/haskell-native-gui"
license:             BSD3
author:              "Callum Lowcay"
maintainer:          "cwslowcay@gmail.com"
copyright:           "2019 Callum Lowcay"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/CLowcay/haskell-native-gui#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  graphics-primitives-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graphics-primitives

tests:
  graphics-primitives-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graphics-primitives
