name:                graphics-primitives
version:             0.1.0.0
github:              "CLowcay/haskell-native-gui"
license:             BSD3
author:              "Callum Lowcay"
maintainer:          "cwslowcay@gmail.com"
copyright:           "2019 Callum Lowcay"

description:         Please see the README on GitHub at <https://github.com/CLowcay/haskell-native-gui#readme>

dependencies:
- array >= 0.5 && < 0.6
- base >= 4.7 && < 5
- colour >= 2.3 && < 2.4
- containers >= 0.6 && < 0.7
- hashable >= 1.2 && < 1.3
- mtl >= 2.2.2 && < 2.3
- unordered-containers >= 0.2.9 && < 0.3

library:
  source-dirs: src
  ghc-options: -Wall

tests:
  graphics-primitives-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graphics-primitives
    - hspec >= 2.6 && < 2.7
